### ISSUE TITLE
search engine optimization

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#165]
Google searches apparently do not show results from COL very high.
See why that is and how that can be improved.
React to blame?

**Comment by gdower** [comment]
Maybe this issue is solved already, but if you look through the indexed search results some of them have a bad title, "HTTP method: GET - The Catalogue of Life":

https://www.google.com/search?q=site:catalogueoflife.org&start=190&sa=N&filter=0&biw=1280&bih=695&dpr=1.5

With a page description of:

"Network Error. HTTP method: GET. Network Error. HTTP method: GET. Distributions. Ecuador (Pichincha), Peru ? We would like to use cookies to measure usage ..."

**Comment by mdoering** [comment]
That doesn't look good. Searching for error in col also finds good page titles, but with the same network error description:
https://www.google.com/search?q=site%3Acatalogueoflife.org+error&biw=1612&bih=925&sxsrf=AOaemvLBIlUn8FLZZ2IHmLfZZNN5Cndqjg%3A1637797365327&ei=9c2eYe-0E_DgsAf2gLmQCA&ved=0ahUKEwivg7LRlrL0AhVwMOwKHXZADoI4vgEQ4dUDCA0&uact=5&oq=site%3Acatalogueoflife.org+error&gs_lcp=Cgdnd3Mtd2l6EANKBAhBGAFQngRYzw5gvhBoAXAAeACAAfsBiAHtCJIBBTAuMy4zmAEAoAEBwAEB&sclient=gws-wiz

**Comment by thomasstjerne** [comment]
I think that pages get a bad header if http://api.catalogueoflife.org/colseo/taxon/<ID> fails.
The headers are inserted in the httpd conf: https://github.com/CatalogueOfLife/deploy/blob/35781964c5fae4f54288f018eb5cc6582bec1159/configs/prod/virt_www.catalogueoflife.org.conf#L14
It should not insert anything if the response code is not 200
