### ISSUE TITLE
Portal (preview): GSD version is missing in the recommended bibliographic citation

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/portal#212]
GSD version is missing in the recommended bibliographic citation (the version is important in the citation).

For example:
https://preview.catalogueoflife.org/data/dataset/2207

![341775649-b95b313e-4eab-4c2f-9fd6-8d523032f534](https://github.com/CatalogueOfLife/portal/assets/28574252/0f0fda50-bed4-4feb-a58d-afcf125a0614)

For attention of @mdoering & @thomasstjerne

**Comment by yroskov** [comment]
Just in case, it should be only **Version** without release date (AKA field "Issued")

**Comment by mdoering** [comment]
This was an intentional change to include the COL version instead. You cannot have both. If we follow the idea of a chapter in a book, the publisher, version and issued date now come from the COL release, not the sources. 

Note that this change is programmatic only, it does not influence what metadata is stored and thus can be reverted. It will also influence how past releases look, as the citation string is not real. It is made up dynamically from the metadata fields based on the styling format we chose. The [march release](https://www.checklistbank.org/dataset/292011/source/2207):

<img width="1436" alt="image" src="https://github.com/CatalogueOfLife/portal/assets/327505/784bb272-fc8b-41d2-93c0-cbabe0fe44eb">
