### ISSUE TITLE
Database Details page 

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/portal#29]
https://www.dev.catalogue.life/data/dataset/1061

![image](https://user-images.githubusercontent.com/28574252/93248763-edac6300-f755-11ea-9e33-301e9a551998.png)

Essential changes needed:

- [ ] Please, add alias to FullGSDName in the heading. For example, **SF Aphid: Aphid Species File** 
Well, it would be nice to add top heading for this page as **Database Details**, and list Short and Full names below:

Short Name: SF Aphid
Full Name: Aphid Species File
Version: 5.0, Jun 2018 Received by CoL: 2018-06-01
etc.

- [x] Authors and Editors. Please replace "and" with "or":  better **Authors/Editors**. GSD may have both authors and editors, but CoL ask them to make a choice for standard bibliographic citation. For example, World Checklist of Selected Plant Families has more than 100 authors, but decided to go ahead with one editor in CoL bibliographic citation. 

- [ ] Standard **Citation** should be generated by backend

**Comment by mdoering** [comment]
- alias: title: This can be quite redundant at times. I dont mind the change but I do also like it as it is
 - Authors/Editors 👍 
 - citation: the API should generate this indeed for the source metadata via `dataset/3LR/source/1010` (which is different from the main datasets metadata). Created [new backend issue](https://github.com/CatalogueOfLife/backend/issues/846)

**Comment by yroskov** [comment]
2020-10-06, more about this page.

https://www.dev.catalogue.life/data/dataset/1146 

- [ ] Bibliographic citation is still missing (i.e. how to cite source dataset). It should be automatically generated using GSD and CoL metadata.

- [ ] It is better to use rank names in statistical headings in plural, e.g. phyla, classes, orders, families, genera, etc.

**Bugs:** 

- [ ] _Authors/Editors._ Author name repeated multiple times 
![image](https://user-images.githubusercontent.com/28574252/95262369-a0219400-07f1-11eb-8126-048e2de3262f.png)

- [ ] _Organisations._ Better use word in singular “Organisation”. Separators (commas or semicolons) are missing between department, organization name, city and country:
![image](https://user-images.githubusercontent.com/28574252/95262438-bd566280-07f1-11eb-9c39-246fbf95e1bf.png)

- [ ] _Geographic scope._ Value “Global” is often missing. I have a feeling that Clearinghouse metadata have a problem with keeping this value in database. 
![image](https://user-images.githubusercontent.com/28574252/95262515-e24ad580-07f1-11eb-8e59-25d5f79934bf.png)

- [ ] Checklist Confidence. There is no context tip which explains stars in this field.
How it works in AC interface (text appears with mouse on stars):
![image](https://user-images.githubusercontent.com/28574252/95262549-f68ed280-07f1-11eb-9127-5f2838af73a4.png)

- [ ] _License._ Missing value in the field License. Many GSDs have “Other” in metadata.
![image](https://user-images.githubusercontent.com/28574252/95262654-250cad80-07f2-11eb-91c7-593a28a2d1af.png)

**Comment by mdoering** [comment]
- ranks in plural: agree thats better, but it needs to be dynamic. @thomasstjerne shall I add a plural attribute to the ranks enum or would you do this frontend wise?
 - source citation: see https://github.com/CatalogueOfLife/backend/issues/846
 - organisation: the UI must render the list nicely and add a delimiter. But the API data is wrong and should use a single string for every organisation. Instead the name, place and country of the organisation is given as separate entries! See https://api.catalogue.life/dataset/3LR/source/1146 and https://api.catalogue.life/dataset/1146 We _could_ consider to create a proper organisation class with name, city, country, etc like we did for contact & author persons. 
 - authors: API or data issue. The source is actually fine: https://api.catalogue.life/dataset/1146
 - Checklist Confidence: instead of a tooltip just for this one how about an about page that describes all metadata items?
 - License: primarily a data issue, it is missing. @thomasstjerne the UI should render "unknown" or sth like that in case of null values though

=> @yroskov @gdower  we need to [go through all metadata](https://github.com/CatalogueOfLife/data/issues/184), verify it and potentially apply updates. I would suggest we do this for one dataset jointly?

**Comment by thomasstjerne** [comment]
> Author name repeated multiple times
This is an error in the data for this specific dataset
